### ISSUE TITLE
Tests are broken since Famix' Parametric update

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/Carrefour#9]
See moosetechnology/Famix#635.

**Comment by badetitou** [comment]
Since this is a major change, I think we can start a v5 branch to follow the changement

**Comment by badetitou** [comment]
As of today, I heard that some bugs exist with the introduction of parametrics, is it already to good moment to update Carrefour?

**Comment by Gabriel-Darbord** [comment]
Which bugs are you referring to?
As I understand it, the problems are with VerveineJ (JDT differences between Windows and other platforms(?)), which leads to incomplete models, not with Famix.

**Comment by NicolasAnquetil** [comment]
All tests of Carrefour were failing.
This was due to:

- CRFTest >> famixModelString having a JSON model with the old format
  I regenerated the model with the latest VerveineJ

- VerveineJ generated model with various "Generalisation" in names, The test (FAST) is expecting the same names with "Generalization" (Z instead of S)
  I manually changed the JSON

After this 74 out of 75 tests are passing. Last one (in `CRFBindingBuildMyClassTest`) uses a class which I cannot find the source for :-(

**Comment by NicolasAnquetil** [comment]
OK, I made de test pass by regenerating a JSON model compatible with the new FAST/Famix.
It is in branch [9-Tests-are-broken-since-Famix-Parametric-update](https://github.com/moosetechnology/Carrefour/tree/9-Tests-are-broken-since-Famix-Parametric-update).

The tests are green for Moose-11, but fail for Moose-10 of course

**Comment by badetitou** [comment]
So let's create the branch v5 from what you did :)
